package models

type AutoGenerated struct {
	ID              string          `json:"_id"`
	Jsonrpc         int             `json:"jsonrpc"`
	Resultvalidator Resultvalidator `json:"resultvalidator"`
}
type Validatorsbyslotnumber struct {
	Slotnumber int      `json:"slotnumber"`
	Leader     string   `json:"leader"`
	Attestors  []string `json:"attestors"`
}
type Resultvalidator struct {
	Epoch                  int                      `json:"epoch"`
	Validatorsbyslotnumber []Validatorsbyslotnumber `json:"validatorsbyslotnumber"`
}
