package db

import (
	"backendAPI/configs"
	"backendAPI/models"
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

func ReturnValidators(pageToken string) (models.AutoGenerated, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	var result models.AutoGenerated
	filter := primitive.D{}
	
	// If page token is provided, add it to the filter
	if pageToken != "" {
		filter = append(filter, primitive.E{Key: "page_token", Value: pageToken})
	}

	err := configs.ValidatorsCollections.FindOne(ctx, filter).Decode(&result)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(result)

	return result, err
}
