package db

import (
	"backendAPI/configs"
	"backendAPI/models"
	"context"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

func ReturnValidators(pageToken string) (models.AutoGenerated, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	var result models.AutoGenerated
	filter := primitive.D{}

	// If page token is provided, add it to the filter
	if pageToken != "" {
		filter = append(filter, primitive.E{Key: "page_token", Value: pageToken})
	}

	err := configs.ValidatorsCollections.FindOne(ctx, filter).Decode(&result)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(result)

	return result, err
}

// CountValidators returns the total number of validators
func CountValidators() (int64, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Get the validators data
	var result models.AutoGenerated
	filter := primitive.D{}
	err := configs.ValidatorsCollections.FindOne(ctx, filter).Decode(&result)
	if err != nil {
		return 0, err
	}

	// Count unique validators (both leaders and attestors)
	uniqueValidators := make(map[string]bool)

	// Process validators by slot
	for _, slotValidators := range result.Resultvalidator.Validatorsbyslotnumber {
		// Add leader
		uniqueValidators[slotValidators.Leader] = true

		// Add attestors
		for _, attestor := range slotValidators.Attestors {
			uniqueValidators[attestor] = true
		}
	}

	return int64(len(uniqueValidators)), nil
}
