package models

type AutoGenerated struct {
	ID              string          `json:"_id"`
	Jsonrpc         int             `json:"jsonrpc"`
	Resultvalidator Resultvalidator `json:"resultvalidator"`
}

type Validatorsbyslotnumber struct {
	Slotnumber int      `json:"slotnumber"`
	Leader     string   `json:"leader"`
	Attestors  []string `json:"attestors"`
}

type Resultvalidator struct {
	Epoch                  int                      `json:"epoch"`
	Validatorsbyslotnumber []Validatorsbyslotnumber `json:"validatorsbyslotnumber"`
}

// ValidatorResponse represents the response format expected by the frontend
type ValidatorResponse struct {
	Validators    []Validator `json:"validators"`
	TotalStaked   string     `json:"totalStaked"`
	NextPageToken string     `json:"next_page_token"`
}

// Validator represents a single validator's information
type Validator struct {
	Address      string  `json:"address"`
	Uptime      float64 `json:"uptime"`
	Age         int     `json:"age"`
	StakedAmount string  `json:"stakedAmount"`
	IsActive    bool    `json:"isActive"`
}
